# ----------------------------
# agondev Makefile
# common library
# ----------------------------

NAME = common
DESCRIPTION = ""

# ----------------------------
include $(shell agondev-config --makefile)
